### ISSUE TITLE
Que mierda

### ISSUE THREAD

**Issue by Playmaker3334** [Playmaker3334/ws_amazon#1]

**Comment by rogeliohdev** [comment]
![RobloxScreenShot20240121_225413355](https://github.com/Playmaker3334/ws_amazon/assets/140979118/2363735f-fd96-4bb0-9efa-3563b88ab37e)

**Comment by Playmaker3334** [comment]
Hola mundo

**Comment by JoaquinMO17** [comment]
Krishna ayudame porfavor vamos a deber esta cosa y vamos a venir en vacaciones (nocierto, pero podria serlo)

**Comment by rogeliohdev** [comment]
wenamechainsama 

![1163915676625403905](https://github.com/Playmaker3334/ws_amazon/assets/140979118/f2d57031-b2be-4d6e-948e-86b6d0afe84f)

![1163915618605600888](https://github.com/Playmaker3334/ws_amazon/assets/140979118/2bd4de12-ec64-446b-a183-215986f9649c)

**Comment by Playmaker3334** [comment]
Felicidades rogeliogod
